global:
  experiment: 99999
  blast_db_name: core_nt.20240803
  blast_db_path: resources/core_nt
  stat_dbss: resources/tree_filter.20240830.dbss
  stat_index: 'resources/tree_index.20240830.dbs'
  stat_annotation: 'resources/tree_filter.20240830.dbss.annotation'
  human_virus_taxlist: 'resources/human_viruses_taxlist.txt'
  out_dir: output
  gettax_sqlite_path: resources/gettax.sqlite
  argos_fasta: "resources/fda-argos-30843.fa.gz"